config/routes.rb
ApplicationSystem::Application.routes.draw do
  resources :visitor_invitations

  root :to => 'visits#index'

  resources :visits

  resources :members

  devise_for :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :name, :user_id
  # attr_accessible :title, :body
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :end_date, :start_date, :visit_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_filter :authenticate_user!

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @visit = Visit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Application System
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %header.navbar.navbar-fixed-top.navbar-inverse.bs-docs-nav
      .container
        .navbar-brand Application System
        %ul.nav.navbar-nav
          %li= link_to 'Log in', 'users/sign_in' if not user_signed_in?
          %li= link_to current_user.email, :root if user_signed_in?
          %li= link_to 'Log out', 'users/log_out' if user_signed_in?
    .container
      - if flash[:notice]
        .alert.alert-success= flash[:notice]
      - elsif flash[:warning]
        .alert.alert-warning= flash[:warning]

      = yield

app/views/visits/_form.html.haml
= simple_form_for(@visit) do |f|
  = f.error_notification

  .form-inputs
    = f.input :start_date
    = f.input :end_date
    = f.input :visit_type

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/visits/edit.html.haml
.page-header
  %h1
    = t(:editing)
    = t('activerecord.models.visit')

= render 'form'

= link_to t(:show), @visit, class: 'btn btn-default'
= link_to t(:back), visits_path, class: 'btn btn-default'

app/views/visits/index.html.haml
.page-header
  %h1 Visits

%table.table.table-striped.table-bordered
  %tr
    %th= t 'activerecord.attributes.visit.start_date'
    %th= t 'activerecord.attributes.visit.end_date'
    %th= t 'activerecord.attributes.visit.visit_type'
    %th

  - @visits.each do |visit|
    %tr
      %td= visit.start_date
      %td= visit.end_date
      %td= visit.visit_type
      %td
        = link_to t(:show), visit, class: 'btn btn-mini btn-default'
        = link_to t(:edit), edit_visit_path(visit),
          class: 'btn btn-mini btn-default'
        = link_to t(:destroy), visit,
          :confirm => t(:are_you_sure, default: "Are you sure?"), :method => :delete,
          class: 'btn btn-mini btn-danger'

%br

= link_to new_visit_path, class: 'btn btn-success' do
  %i.icon-plus.icon-white
  = t(:new_visit)

app/views/visits/new.html.haml
.page-header
  %h1= t(:new_visit)

= render 'form'

= link_to t(:back), visits_path, class: 'btn btn-default'

app/views/visits/show.html.haml
%p
  %b Start date:
  = @visit.start_date
%p
  %b End date:
  = @visit.end_date
%p
  %b Type:
  = @visit.visit_type

= link_to t(:edit), edit_visit_path(@visit), class: 'btn btn-default'
= link_to t(:back), visits_path, class: 'btn btn-default'